[main]
cmd = "../target/release/wasm-runner"
args = [
    "--wasm",
    "../target/wasm32-unknown-unknown/release/_2mm.wasm",
    "--fuel",
    "1000",
    "--fuel",
    "100000",
    "--count",
    "2",
]
cpu_core = 12

[intruders]

[intruders.stress]
cmd = "stress-ng"
args = ["--class", "cpu-cache", "--all", "1"]
cpu_core = 14
