primary = [0, 0]

[processes]

[processes.wasm]
id = [0, 0]
cmd = "./target/release/wasm-runner"
args = [
    "--wasm",
    "./target/wasm32-unknown-unknown/release/wasm-payload.wasm",
    "--fuel",
    "10000",
    "--wctpf",
    "1000000000",
    "--wctpf",
    "0",
    "--wctpf",
    "25000",
    "--count",
    "100",
]
cpu_core = 6
ipc_arg = "--ipc"

[processes.stress]
args = ["--class", "cpu-cache", "--seq", "1", "-t", "60m"]
id = [1, 0]
cmd = "stress-ng"
cpu_core = 7

# kernel cmdline:
# 5950x:        nohz_full=6-7,22-23 isolcpus=domain,managed_irq,6-7,22-23 irqaffinity=0-5,8-21,24-31
# i9-14900K:    nohz_full=12-15 isolcpus=domain,managed_irq,12-15 irqaffinity=0-11,16-31
