primary = [0, 0]

[processes]

[processes.wasm]
id = [0, 0]
cmd = "../target/release/wasm-runner"
args = [
    "--wasm",
    "../target/wasm32-unknown-unknown/release/_2mm.wasm",
    "--fuel",
    "10000",
    "--count",
    "100",
    "--wc-tpf",
    "1",
]
cpu_core = 6
ipc_arg = "--ipc"

[processes.stress]
args = ["--class", "cpu-cache", "--seq", "1", "-t", "5m"]
id = [1, 0]
cmd = "stress-ng"
cpu_core = 7
